### ISSUE TITLE
Catalog of my things kanban board  setup

### ISSUE THREAD

**Issue by AbuTalha3** [AbuTalha3/catalog-of-my-things#38]
Here is the link to our project "https://github.com/AbuTalha3/catalog-of-my-things/projects/1"
We are a group of three members

**Comment by OyePriscilla** [comment]
Hi @AbuTalha3, @jkanyi-web and @siddghosh108 👏 👏, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly use the [previous link](https://github.com/AbuTalha3/catalog-of-my-things/issues/5) that you used to request for review for the purpose of consistency and don't forget to implement all the required changes. 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
