### ISSUE TITLE
Catalog-of-things-kanban-board

### ISSUE THREAD

**Issue by siddghosh108** [AbuTalha3/catalog-of-my-things#5]
The link to the kanban link project is as follows:
https://github.com/AbuTalha3/catalog-of-my-things/projects/1
We have 3 members in our team
Team member#1 Abu Talha
Team Member#2 Siddhartha Ghosh
Team Member#3 Victor Kanyi

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @jkanyi-web, @AbuTalha3 and @siddghosh108,

Good job so far!
✔️ Well-assigned tasks
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] All the tasks are parked into one issue. Kindly split up the tasks to be distinct, so that each item on the list of requirements has its corresponding issue.

  ![image](https://github.com/AbuTalha3/catalog-of-my-things/assets/36542986/4be27ee6-ed8d-4a3d-99f7-3c5f0d4e7131)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @jkanyi-web, @AbuTalha3 and @siddghosh108,

## Highlights
✔️ Assigned tasks

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] Kindly add the remaining group tasks.

  ![image](https://github.com/AbuTalha3/catalog-of-my-things/assets/54848363/b63b3d03-c1f7-4168-819a-b660971d645f)

- [ ] Kindly ensure all your tasks have descriptions. These are just example tasks that have no description - there are many of them.

  ![image](https://github.com/AbuTalha3/catalog-of-my-things/assets/54848363/53fe1f2a-b2f9-4bb5-a9e1-61f4234889fd)

  ![image](https://github.com/AbuTalha3/catalog-of-my-things/assets/54848363/42ec7282-1e4e-429e-aca5-b84af480f627)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi @jkanyi-web, @AbuTalha3 and @siddghosh108, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* I cannot find the link to the kanban. You appear to have unlinked the project that was attached to this issue. Kindly add the link to the kanban project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by OyePriscilla** [comment]
Hi @jkanyi-web, @AbuTalha3 and @siddghosh108 👏 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Added project link to issue description ✔️ 
All tasks have description ✔️ 
Added missing tasks ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
